# Generated by Django 4.0.3 on 2022-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0002_alter_ti_ticketsinfos_e_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_users',
            name='u_happy_lucky_birthday',
            field=models.DateField(),
        ),
    ]
