# Generated by Django 4.0.3 on 2022-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0003_alter_u_users_u_happy_lucky_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_places',
            name='p_ido',
            field=models.DecimalField(blank=True, decimal_places=5, default=99, max_digits=7),
        ),
        migrations.AlterField(
            model_name='u_users',
            name='u_mail_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='u_users',
            name='u_phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
