# Generated by Django 4.0.3 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0005_alter_e_events_e_end_alter_e_events_e_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_addresses',
            options={'verbose_name_plural': '住所'},
        ),
        migrations.AlterModelOptions(
            name='c_charges',
            options={'verbose_name_plural': '料金'},
        ),
        migrations.AlterModelOptions(
            name='cc_chargeclasses',
            options={'verbose_name_plural': '料金区分'},
        ),
        migrations.AlterModelOptions(
            name='e_events',
            options={'verbose_name_plural': 'イベント'},
        ),
        migrations.AlterModelOptions(
            name='en_enries',
            options={'verbose_name_plural': '入場'},
        ),
        migrations.AlterModelOptions(
            name='m_maxes',
            options={'verbose_name_plural': '定員'},
        ),
        migrations.AlterModelOptions(
            name='n_nfcs',
            options={'verbose_name_plural': 'NFC'},
        ),
        migrations.AlterModelOptions(
            name='o_others',
            options={'verbose_name_plural': 'その他'},
        ),
        migrations.AlterModelOptions(
            name='oo_ticket_connect_charge_oo',
            options={'verbose_name_plural': 'チケット料金中間テーブル'},
        ),
        migrations.AlterModelOptions(
            name='p_places',
            options={'verbose_name_plural': '開催地'},
        ),
        migrations.AlterModelOptions(
            name='s_seats',
            options={'verbose_name_plural': '座席情報'},
        ),
        migrations.AlterModelOptions(
            name='sc_seatclasses',
            options={'verbose_name_plural': '座席区分'},
        ),
        migrations.AlterModelOptions(
            name='t_tickets',
            options={'verbose_name_plural': 'チケット'},
        ),
        migrations.AlterModelOptions(
            name='ti_ticketsinfos',
            options={'verbose_name_plural': 'チケット情報'},
        ),
        migrations.AlterModelOptions(
            name='u_users',
            options={'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='uc_userclasses',
            options={'verbose_name_plural': 'ユーザー区分'},
        ),
        migrations.AlterModelOptions(
            name='ww_charges_ww',
            options={'verbose_name_plural': '料金中間テーブル'},
        ),
        migrations.AlterModelOptions(
            name='yy_eventtags',
            options={'verbose_name_plural': 'イベントタグ'},
        ),
        migrations.AlterModelOptions(
            name='zz_events_connect_tags_zz',
            options={'verbose_name_plural': 'イベントタグ中間テーブル'},
        ),
        migrations.RemoveField(
            model_name='p_places',
            name='p_region',
        ),
        migrations.AlterField(
            model_name='a_addresses',
            name='a_build',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='e_events',
            name='e_end',
            field=models.DateField(blank=True, default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='e_events',
            name='e_start',
            field=models.DateField(blank=True, default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='p_places',
            name='p_prefecture',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ti_ticketsinfos',
            name='ti_end',
            field=models.DateField(blank=True, default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='ti_ticketsinfos',
            name='ti_start',
            field=models.DateField(blank=True, default='1111-11-11'),
        ),
    ]
