# Generated by Django 4.0.3 on 2022-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0006_alter_a_addresses_options_alter_c_charges_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_places',
            name='p_prefecture',
            field=models.CharField(max_length=5),
        ),
    ]
