# Generated by Django 4.0.3 on 2022-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0007_alter_p_places_p_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_places',
            name='p_ido',
            field=models.CharField(blank=True, default='99', max_length=16),
        ),
        migrations.AlterField(
            model_name='p_places',
            name='p_kedo',
            field=models.CharField(blank=True, default='360', max_length=17),
        ),
    ]
