# Generated by Django 4.0.3 on 2022-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0008_alter_p_places_p_ido_alter_p_places_p_kedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_events',
            name='e_end',
            field=models.DateTimeField(blank=True, default='1111-11-11 00:00'),
        ),
        migrations.AlterField(
            model_name='e_events',
            name='e_start',
            field=models.DateTimeField(blank=True, default='1111-11-11 00:00'),
        ),
    ]
