# Generated by Django 4.0.3 on 2022-03-11 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0009_alter_e_events_e_end_alter_e_events_e_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='ww_charges_ww',
            name='e_event_id',
            field=models.ForeignKey(db_column='e_event_id', default=111111, on_delete=django.db.models.deletion.CASCADE, to='hanken2.e_events'),
            preserve_default=False,
        ),
    ]
