# Generated by Django 4.0.3 on 2022-03-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0011_alter_s_seats_t_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_maxes',
            name='m_capacity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
