# Generated by Django 4.0.3 on 2022-03-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanken2', '0018_t_tickets_ww_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tickets',
            name='ww_charge_id',
            field=models.ForeignKey(db_column='ww_charge_id', on_delete=django.db.models.deletion.CASCADE, to='hanken2.ww_charges_ww'),
        ),
    ]
